### ISSUE TITLE
http fault fixedDelay different with istio virtualservice crd

### ISSUE THREAD

**Issue by champly** [mosn/mosn#1093]
### Describe the bug

istio config virtualservice fault fixedDelay transform ns

virtualservice:

```yaml
kind: VirtualService
metadata:
  name: ratings
  namespace: default
spec:
  hosts:
  - ratings
  http:
  - fault:
      delay:
        fixedDelay: 7s
        percentage:
          value: 100
    match:
    - headers:
        end-user:
          exact: jason
    route:
    - destination:
        host: ratings
        subset: v1
  - route:
    - destination:
        host: ratings
        subset: v1
```

through xDS push mosn sidecar，route get 7ns

```json
{
......
    "per_filter_config":{
        "fault":{
            "abort":{

            },
            "delay":{
                "fixed_delay":"7ns",
                "percentage":100
            }
        }
    }
......
}
```

### Environment

- MOSN branch: feature-istio_adapter
