### ISSUE TITLE
支持 Address_Pipe 类型的 endpoint

### ISSUE THREAD

**Issue by GLYASAI** [mosn/mosn#1314]
### The New Feature

istio 的测试用例里面, 有用到 Address_Pipe 类型的 endpoint, 如下:

```yaml
- name: sds-grpc
    type: STATIC
    http2_protocol_options: {}
    connect_timeout: 5s
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: outbound_cluster_tls
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              pipe:
                path: /tmp/sdstestudspath.20231
```

mosn 目前只支持 IP:PORT 类型的 endpoint, 未支持 Address_Pipe 类型的 endpoint.

### Your scenes

当然, 有 IP:PORT 类型的 endpoint 也足够了. 但是, 考虑到[Optimize Istio test framework](https://github.com/istio/istio/issues/24463), 是否也可以支持Address_Pipe 类型的 endpoint.
