### ISSUE TITLE
作为sidecar的时候，应用接收https请求问题

### ISSUE THREAD

**Issue by misinibaba** [mosn/mosn#2268]
我使用的mosnio/proxyv2:v1.0.0-1.10.6镜像，作为istio的sidecar使用
启动命令为：
istioctl manifest apply --set profile=demo --set .values.global.proxy.image="mosnio/proxyv2:v1.0.0-1.10.6" --set meshConfig.defaultConfig.binaryPath="/usr/local/bin/mosn"

然后我启动了一个pod foo监听443请求，并创建了对应的svc，然后启动了另一个pod,使用curl -k https://foo
返回错误为
curl: (35) TCP connection reset by peer
command terminated with exit code 35

测试了几种情况，以下均是在istio中作为sidecar测试的：
![ScreenShot_20230327_153728107](https://user-images.githubusercontent.com/17180235/227874532-7ec3cbc4-d023-43ff-9487-2148adef6fb5.png)

envoy则能正常接收到443数据

- MOSN Image Version
- mosnio/proxyv2:v1.0.0-1.10.6

期待答复

**Comment by doujiang24** [comment]
@misinibaba 多谢反馈，可以提供更多具体的配置，比如 svc 创建的配置，方便我们复现排查

@3062 可以来测试复现一下的

**Comment by misinibaba** [comment]
@doujiang24 你好，
svc配置如下
```
apiVersion: v1
kind: Service
metadata:
     name: go-ssl
spec:
     ports:
          - port: 443
             targetPort: 443
     selector:
        app: go-ssl
```

开发环境为离线脱网环境
容器则启动了一个name为go-ssl的只有一个pod的deployment,监听0.0.0.0:443端口
