### ISSUE TITLE
RouterConfig for rpc routing

### ISSUE THREAD

**Issue by EZLippi** [mosn/mosn#980]
### Your question
suppose we want to use x-protocol in mesh environment, maybe we will use some property in request headers for request Routing, just like sofaRpc use 'service' header to router, as the code below :
```			 {
			   "type":"connection_manager",
			   "config":{
				 "router_config_name":"server_router",
				 "virtual_hosts":[{
				   "name":"serverHost",
				   "domains": ["*"],
				   "routers": [
					 {
					   "match":{"headers":[{"name":"service","value":".*"}]},
					   "route":{"cluster_name":"serverCluster"}
					 }
				   ]
				 }]
			   }
```
does it mean whenever some rpc service is added in mesh network, we have to create a virtualService in mesh for routing, for example, i have a rpc service named order-service, we use 'service' header for routing, then i have to add something like this:
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: order-server
spec:
  http:
  - match:
    - headers:
        service:
          exact: order-service
    route:
    - destination:
        host: order-service
```
if i have 3000 services, does it mean i have to add 3000 virtualService?

### Environment

- MOSN Version

### Logs

- Paste the logs you see.
